import type { CargoCard, PassengerCard } from './types'

export const PASSENGERS: PassengerCard[] = [
  {
    id: 'grandma',
    name: 'Бабуся Оля',
    payout: 90,
    patience: 0.85,
    hunger: 0.4,
    chaos: 0.15,
    blurb: 'Тиха, але чай має бути гарячим.',
    color: '#d9a066',
  },
  {
    id: 'influencer',
    name: 'Інфлюенсер',
    payout: 160,
    patience: 0.3,
    hunger: 0.7,
    chaos: 0.6,
    blurb: 'Знімає Stories під час турбулентності.',
    color: '#ff7eb6',
  },
  {
    id: 'business',
    name: 'Бізнес-клас?',
    payout: 180,
    patience: 0.22,
    hunger: 0.55,
    chaos: 0.45,
    blurb: 'Купив економ, вимагає шампанське.',
    color: '#4d6a8a',
  },
  {
    id: 'kids',
    name: 'Діти + барабан',
    payout: 120,
    patience: 0.28,
    hunger: 0.9,
    chaos: 0.8,
    blurb: 'Енергія нескінченна. Барабан теж.',
    color: '#f4d35e',
  },
  {
    id: 'sleepy',
    name: 'Сонний студент',
    payout: 75,
    patience: 0.92,
    hunger: 0.25,
    chaos: 0.1,
    blurb: 'Майже ідеальний пасажир. Майже.',
    color: '#7ec8c3',
  },
  {
    id: 'karate',
    name: 'Каратист',
    payout: 170,
    patience: 0.4,
    hunger: 0.5,
    chaos: 0.7,
    blurb: 'Розминається в проході. Сильно.',
    color: '#ff6b4a',
  },
]

export const CARGO: CargoCard[] = [
  {
    id: 'mail',
    name: 'Мішки з поштою',
    payout: 100,
    weight: 0.3,
    volatility: 0.12,
    blurb: 'Нудно, але стабільно.',
    color: '#8b7355',
  },
  {
    id: 'fish',
    name: 'Жива риба',
    payout: 190,
    weight: 0.45,
    volatility: 0.55,
    blurb: 'Акваріум любить турбулентність.',
    color: '#3d8ea5',
  },
  {
    id: 'piano',
    name: 'Рояль «трохи»',
    payout: 240,
    weight: 0.9,
    volatility: 0.5,
    blurb: 'Важкий. І скрипить пісню смерті.',
    color: '#2a2a2a',
  },
  {
    id: 'bees',
    name: 'Вулики',
    payout: 220,
    weight: 0.4,
    volatility: 0.85,
    blurb: 'Не відкривай. Серйозно.',
    color: '#f0c75e',
  },
  {
    id: 'cake',
    name: 'Весільний торт',
    payout: 150,
    weight: 0.35,
    volatility: 0.65,
    blurb: 'Один крен — і кінець романтики.',
    color: '#f7d6e0',
  },
  {
    id: 'mystery',
    name: '«Не питайте»',
    payout: 320,
    weight: 0.55,
    volatility: 0.95,
    blurb: 'Максимальний кеш. Мінімум пояснень.',
    color: '#6b2d5c',
  },
]

export const MAX_PASSENGERS = 4
export const MAX_CARGO = 3
export const FLIGHT_SECONDS = 95
